    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    zn "USER"
    do EnableDeepSee^%SYS.cspServer("/csp/user/")
    
    ; install samples-bi to have cubes with test data
    zpm "install samples-bi"

    ; load app
    zpm "load /opt/irisapp"

    Do $system.OBJ.LoadDir("/opt/irisapp/Samples","ck",,1)
    Do ##class(%DeepSee.TermList).%ImportCSV("/opt/irisapp/Assets/Mapbox/ISO3166.csv")